config/routes.rb
AuthTest::Application.routes.draw do
  root :to => "pages#home"

	resources :projects do
		resources :tasks
	end
	
	resources :tasks
  devise_for :users

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, :dependent => :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :projects
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = current_user.projects.all
	end
	
	def new
		@project = Project.new
	end
	
	def create
		@project  = current_user.projects.build(params[:project])
		
		if @project.save
    	flash[:success] = "Project created!"
    	redirect_to projects_path
 	 	else
    	render 'pages/home'
  	end
	end
	
	def destroy
		@project = Project.find(params[:id])
		if @project.destroy
			flash[:success] = "Project deleted!"
			redirect_to projects_path
		end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
	def show
		@task = Task.find(params[:id])
	end
	
	def new
		@project = Project.find(params[:project_id])
		@task = @project.tasks.build
	end
	
	def create
		@project = Project.find(params[:project_id])
		@task  = @project.tasks.build(params[:task])
		
		if @task.save
			flash[:success] = "Task saved"
			redirect_to task_path(@task)
		else
			render 'task/new'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthTest</title>
  <%= stylesheet_link_tag 'blueprint/screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div class="container">
	<div id="user_nav">
		<% if user_signed_in? %>
		  Signed in as <%= current_user.email %>. Not you?
		  <%= link_to "Sign out", destroy_user_session_path %> - 
		  <%= link_to "Edit Profile", edit_user_registration_path %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
		<% end %>
	</div>

	<% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
	<% end %> 


	<%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>
<%= link_to "Projects", projects_path %>

app/views/projects/index.html.erb
<% if @projects.count == 0 %> 
	<p>No projects to display</p>
<% end %>
	
	
	<%= link_to "Add a new one", new_project_path %>

<% @projects.each do |p| %>
	<h2><%= p.name %></h2>
	<%= link_to "Remove Project", p, :confirm => 'Are you sure?', :method => :delete %> - 
	<%= link_to "New Task", new_project_task_path(p) %>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
	<div class="field">
		<%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<p>
	Enter time spent for project: <%= @project.name %>
</p>
<% form_for [@project, @task] do |f| %>
	<%= f.label :time_spent %>
	<%= f.text_field :time_spent %>
	<%= f.submit "Submit" %>
<% end %>

app/views/tasks/show.html.erb
<%= @task.time_spent %>